# Generated by Django 5.0.14 on 2026-05-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=120, verbose_name='Soyad')),
                ('father_name', models.CharField(blank=True, max_length=120, verbose_name='Ata adı')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon')),
                ('parent_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Valideyn telefonu')),
                ('class_group', models.CharField(max_length=64, verbose_name='Sinif / Qrup')),
                ('registration_date', models.DateField(verbose_name='Qeydiyyat tarixi')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Passiv')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Qeyd')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Arxiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='students_st_last_na_3e473b_idx'), models.Index(fields=['class_group'], name='students_st_class_g_21b4c1_idx'), models.Index(fields=['is_archived', 'status'], name='students_st_is_arch_377def_idx')],
            },
        ),
    ]
