# Generated by Django 5.0.14 on 2026-05-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Qrupun adı')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aylıq ödəniş (₼)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_tuition',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 olsa, seçilmiş qrupun aylığı tətbiq olunur.', max_digits=12, verbose_name='Fərdi aylıq ödəniş (₼)'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.studentgroup', verbose_name='Qrup'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_group'], name='students_st_student_52d324_idx'),
        ),
    ]
