# Generated by Django 5.0.14 on 2026-05-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentgroup_and_student_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.CharField(max_length=64, verbose_name='Qrup'),
        ),
    ]
