# Generated by Django 5.0.14 on 2026-05-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_class_group_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Qrup (sinxron)'),
        ),
    ]
