# Generated by Django 5.0.14 on 2026-05-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_class_group_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="lesson_weekdays",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Həftənin dərs keçirilən günləri.",
                max_length=32,
                verbose_name="Dərs günləri",
            ),
        ),
    ]
