# Generated by Django 5.0.14 on 2026-05-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_academic_year_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ['academic_year_start', 'name']},
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_academi_3b240e_idx',
            old_name='students_st_academi_8a1b2c_idx',
        ),
    ]
