# Generated by Django 5.0.14 on 2026-05-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aylıq sınaq', max_length=200, verbose_name='Sınağın adı')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('subject_scores', models.JSONField(default=dict, help_text='Məs: {"Riyaziyyat": 18, "Azərbaycan dili": 15}')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('max_total', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('teacher_notes', models.TextField(blank=True, default='', verbose_name='Müəllim qeydi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['student', 'year', 'month'], name='exams_examr_student_71d6b6_idx')],
            },
        ),
    ]
