# Generated by Django 5.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
        ("students", "0006_academic_year_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyExam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120, verbose_name="Sınağın adı")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Sıra")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_exams",
                        to="students.studentgroup",
                        verbose_name="Qrup",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="monthlyexam",
            index=models.Index(fields=["student_group", "sort_order"], name="exams_monthl_student_7c8a1e_idx"),
        ),
        migrations.CreateModel(
            name="MonthlyExamScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score_percent", models.DecimalField(decimal_places=2, max_digits=5, verbose_name="Faiz (%)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "monthly_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="exams.monthlyexam",
                        verbose_name="Aylıq sınaq",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_exam_scores",
                        to="students.student",
                        verbose_name="Tələbə",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monthlyexamscore",
            constraint=models.UniqueConstraint(
                fields=("monthly_exam", "student"),
                name="exams_monthlyexamscore_exam_student_uniq",
            ),
        ),
    ]
