# Generated by Django 5.0.14 on 2026-05-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_monthlyexam_monthlyexamscore'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyexam',
            new_name='exams_month_student_e847b6_idx',
            old_name='exams_monthl_student_7c8a1e_idx',
        ),
    ]
